package errors

// los dose se llaman igual no esntrr√°n en conflicto? al userlo se renemobra y no pasa nada
import "errors"

var ErrOrderNotFound = errors.New("order-not-found")